# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 06:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mmmoney", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="personal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="personal list",
            ),
        )
    ]
